# Project: 项目1
# Makefile created by Dev-C++ 5.11

CPP      = g++.exe
CC       = gcc.exe
WINDRES  = windres.exe
OBJ      = main.o acllib.o
LINKOBJ  = main.o acllib.o
LIBS     = -L"D:/DEV/Dev-Cpp/MinGW64/lib" -L"D:/DEV/Dev-Cpp/MinGW64/x86_64-w64-mingw32/lib" -static-libgcc -mwindows -mwindows  -lwinmm  -lgdi32  -lkernel32  -lmsimg32 -lole32  -loleaut32  -luser32  -luuid
INCS     = -I"D:/DEV/Dev-Cpp/MinGW64/include" -I"D:/DEV/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"D:/DEV/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include"
CXXINCS  = -I"D:/DEV/Dev-Cpp/MinGW64/include" -I"D:/DEV/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"D:/DEV/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include" -I"D:/DEV/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include/c++"
BIN      = 项目1.exe
CXXFLAGS = $(CXXINCS) -DWINVER=0x0500
CFLAGS   = $(INCS) -DWINVER=0x0500
RM       = rm.exe -f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CC) $(LINKOBJ) -o $(BIN) $(LIBS)

main.o: main.c
	$(CC) -c main.c -o main.o $(CFLAGS)

acllib.o: acllib.c
	$(CC) -c acllib.c -o acllib.o $(CFLAGS)
